spring:
  datasource:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/mc_orderdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true&rewriteBatchedStatements=true&profileSQL=true
#      url: jdbc:mysql://localhost:3306/mc_orderdb?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
      username: root
      password: root

mybatis:
  mapper-locations: classpath:mapper/*.xml
