server:
  port: 8763

spring:
  application:
    name: order-service
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_db_05?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_db_06?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
    sharding:
      tables:
        # 按照下单人id分两个库，每个库按照订单id分16张表
        order_master_brief:
          actual-data-nodes: ds$->{0..1}.order_master_brief_$->{0..15}
          database-strategy:
            inline:
              sharding-column: customer_id
              algorithm-expression: ds$->{customer_id % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_master_brief_$->{id % 16}
        account_brief:
          actual-data-nodes: ds0.account_brief_$->{0..1}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: account_brief_$->{id % 2}
    props:
      sql:
        show: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    #服务过期时间配置,超过这个时间没有接收到心跳，EurekaServer就会将这个实例剔除
    #注意，EurekaServer一定要设置eureka.server.eviction-interval-timer-in-ms否则这个配置无效，这个配置一般为服务刷新时间配置的三倍
    #默认90s
    lease-expiration-duration-in-seconds: 15
    #服务刷新时间配置，每隔这个时间会主动心跳一次
    #默认30s
    lease-renewal-interval-in-seconds: 5