server:
  port: 8761

eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    server:
      #eureka server刷新readCacheMap的时间，注意，client读取的是readCacheMap，这个时间决定了多久会把readWriteCacheMap的缓存更新到readCacheMap上
      #默认30s
      responseCacheUpdateIntervalMs: 3000
      #启用主动失效，并且每次主动失效检测间隔为3s
      eviction-interval-timer-in-ms: 3000

spring:
  application:
    name: eurka-server
