spring:
  shardingsphere:
    datasource:
      names: ds0,ds1
      ds0:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_db_05?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
      ds1:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/test_db_06?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
        username: root
        password: root
    sharding:
      tables:
        # 按照下单人id分两个库，每个库按照订单id分16张表
        order_master_brief:
          actual-data-nodes: ds$->{0..1}.order_master_brief_$->{0..15}
          database-strategy:
            inline:
              sharding-column: customer_id
              algorithm-expression: ds$->{customer_id % 2}
          table-strategy:
            inline:
              sharding-column: id
              algorithm-expression: order_master_brief_$->{id % 16}
    props:
      sql:
        show: true

# 分库分表
#spring:
#  shardingsphere:
#    datasource:
#      names: ds0,ds1
#      ds0:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test_db_01?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: root
#      ds1:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test_db_02?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: root
#    sharding:
#      tables:
#        user_info:
#          actual-data-nodes: ds0.user_info_$->{0..1}
#          table-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: user_info_$->{id % 2}
#        dept_info:
#          actual-data-nodes: ds$->{0..1}.dept_info
#          database-strategy:
#            inline:
#              sharding-column: id
#              algorithm-expression: ds$->{id % 2}
#    props:
#      sql:
#        show: true

# 读写分离
#spring:
#  shardingsphere:
#    datasource:
#      names: primary,second
#      primary:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test_db_03?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: root
#      second:
#        type: com.alibaba.druid.pool.DruidDataSource
#        driver-class-name: com.mysql.cj.jdbc.Driver
#        url: jdbc:mysql://localhost:3306/test_db_04?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=true
#        username: root
#        password: root
#    masterslave:
#      name: ms
#      master-data-source-name: primary
#      slave-data-source-names: second
#    props:
#      sql:
#        show: true
